### ISSUE TITLE
Failed to run frr with wasmtime: Can't create pid lock file /var/run/frr/watchfrr.pid (No such file or directory), exiting

### ISSUE THREAD

**Issue by hsluoyz** [ktock/container2wasm#131]
I am trying to run FRRouting (a BGP routing software in C) in wasmtime, I have successfully converted the Docker image: https://hub.docker.com/r/frrouting/frr to .wasm file.

![image](https://github.com/ktock/container2wasm/assets/3787410/73fa31b6-80dd-4c25-850c-4973a6fc3f69)

But when running with wasmtime, it gets error:

`
F:\container2wasm\cmd\c2w>wasmtime frr.wasm
2023/09/14 02:47:51 WATCHFRR: [XNZM2-2XF6G][EC 100663303] Can't create pid lock file /var/run/frr/watchfrr.pid (No such file or directory), exiting
`

My env:

- OS: Win 11 22H2 x64
- container2wasm: master HEAD
- Wasmtime: latest version installer: https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-windows.msi
- FRRouting image: latest tag

Update:

I also tested on WSL (Ubuntu) with wasmtime and the result is the same (I just reused the same frr.wasm, which is built by container2wasm on Windows):

![image](https://github.com/ktock/container2wasm/assets/3787410/46698eb6-edfc-488a-affb-54dcd784f2fb)

![image](https://github.com/ktock/container2wasm/assets/3787410/f9a3ba0c-0fff-4773-ad2a-4f5ad3ca1777)

How to resolve it? Thanks!

**Comment by ktock** [comment]
@hsluoyz Thanks for reporting this. I believe I've just fixed this in v0.5.1 (#132). Could you try v0.5.1?

**Comment by hsluoyz** [comment]
This issue has been resolved, thanks for the quick fix!
