### ISSUE TITLE
zsh: exec format error: c2w

### ISSUE THREAD

**Issue by flavioespinoza** [ktock/container2wasm#319]
MacOS Sonoma 14.6.1
x86_64
GOOS = linux
GOARCH = amd64

```
❯ go version
go version go1.21.13 darwin/amd64
```

I keep getting this error
````
❯ c2w secondstate/rust-example-hello out.wasm
zsh: exec format error: c2w
```

**Comment by ktock** [comment]
Mac support isn't completed (#198). Can you run this in a Linux VM?

**Comment by ktock** [comment]
Closing this because of duplication with #198.
