### ISSUE TITLE
How to execute the ARM64 container with qemu tcg and emscripten.

### ISSUE THREAD

**Issue by yomaytk** [ktock/container2wasm#323]
Hello, I tried executing the ARM64 container with emscripten following the command in [examples/emscripten-qemu-tcg](https://github.com/ktock/container2wasm/tree/main/examples/emscripten-qemu-tcg).
Looking at the command, it seems that we should specify the option `--target-stage`. 
Then, I tried some options `--target-stage=js-qemu-aarch64`, `--target-stage=js-qemu-arm64` but those target stages could not be found.

If container2wasm can convert the ARM64 container with qemu tcg and emscripten, could you tell me the command? Thanks.

**Comment by ktock** [comment]
Arm64 guest isn't currently implemented for TCG+emscripten. But you can try TCI (https://github.com/ktock/container2wasm/tree/qemu-tci-emscripten-aarch64).

**Comment by yomaytk** [comment]
Ok, Thanks!
