### ISSUE TITLE
How to convert a container that already exists on the host machine to a WASM?

### ISSUE THREAD

**Issue by FunnyCorgi** [ktock/container2wasm#325]
How do I convert a container that already exists on the host machine to a WASM?

**Comment by ktock** [comment]
@FunnyCorgi If you have a image of the container, you can just convert it into wasm using `c2w` command as described in README. If you don't have the image of the container, you need to acquire the image by pulling it from somewhere or by generating it using [`docker commit`](https://docs.docker.com/reference/cli/docker/container/commit/) or something.

**Comment by FunnyCorgi** [comment]
Thank you, this should help.
