### ISSUE TITLE
Wasmer Freezes Up

### ISSUE THREAD

**Issue by cemalgnlts** [ktock/container2wasm#71]
Hi,

When I try in Wasmer I get no response:

```sh
@cemalgnlts ➜ /workspaces/codespaces-blank $ time wasmtime riscv-node.wasm
Welcome to Node.js v18.16.0.

Type ".help" for more information.
> .exit
.exit

real    0m13.176s
user    0m10.205s
sys     0m0.213s

@cemalgnlts ➜ /workspaces/codespaces-blank $ time wasmer run riscv-node.wasm 
^C
real    0m39.833s
user    0m0.087s
sys     0m0.143s

@cemalgnlts ➜ /workspaces/codespaces-blank $ 
```

**Comment by ktock** [comment]
You need to pass `--no-stdin` to avoid blocking (e.g. `wasmer out.wasm -- --no-stdin echo hello`). AFAIK (as mentioned in https://github.com/ktock/container2wasm#wasi-runtimes-integration-status ), wasmer doesn't seem to support non-blocking stdin (i.e. `select` syscall on stdin) so this needs to be fixed for making stdio work on wasmer properly.

**Comment by cemalgnlts** [comment]
Yes, it works now, thanks.
