### ISSUE TITLE
Error on wasi-browser example: `SharedArrayBuffer is not defined`

### ISSUE THREAD

**Issue by Randark-JMT** [ktock/container2wasm#97]
Following the tutorial at this link [/examples/wasi-browser](https://github.com/ktock/container2wasm/tree/main/examples/wasi-browser) , I managed to generate the wasm file, but the browser reported an error

![图片](https://github.com/ktock/container2wasm/assets/56223739/de6b0182-f4aa-4bfc-88a0-9a2c58083cb8)

And you can find the error message in your browser's console.

![图片](https://github.com/ktock/container2wasm/assets/56223739/e13464de-2583-4f3b-bc35-a5a73b3c922d)

**Comment by ktock** [comment]
@Randark-JMT  Thanks for trying this. According to the error message, you need to enable SharedArrayBuffer to make xterm-pty work. If you use apache http server, you need to add the headers something like this:

https://github.com/ktock/container2wasm/blob/93665e3652dcc458ae5b06c88ebd1f55cd7ccd3b/examples/wasi-browser/xterm-pty.conf#L1-L2

You can also find further information on xterm-pty repo. https://github.com/mame/xterm-pty#emscripten-integration

**Comment by Randark-JMT** [comment]
Yes, according to the instructions given in the sample, the relevant conf files and parameters have indeed been loaded in

![图片](https://github.com/ktock/container2wasm/assets/56223739/810bac42-d91b-45d0-9066-b0c6d142d9e1)

But for some reason, the phrase "Include conf/extra/xterm-pty.conf" didn't take effect, and my browser continued to report the error

**Comment by ktock** [comment]
It seems that you are sharing [xterm-pty.conf](https://github.com/ktock/container2wasm/blob/93665e3652dcc458ae5b06c88ebd1f55cd7ccd3b/examples/wasi-browser/xterm-pty.conf#L1-L2) to the server by `-v "/tmp/out-js2/xterm-pty.conf:/usr/local/apache2/conf/extra/xterm-pty.conf:ro"`. Can you make sure you've created `/tmp/out-js2/xterm-pty.conf` on your machine?

**Comment by Randark-JMT** [comment]
yeah, I can confirm that this is not the problem, and I've already solved it

Based on the information in ["stackoverflow - SharedArrayBuffer is not defined" error in cloud server but working in localhost](https://stackoverflow.com/questions/74623993/sharedarraybuffer-is-not-defined-error-in-cloud-server-but-working-in-localhos)], I can determine that https is required for the SharedArrayBuffer related features to work properly

![图片](https://github.com/ktock/container2wasm/assets/56223739/b63dc9b1-54d5-477b-bf21-5d92891e9d86)

So I wrote my own copy of the nginx Dockerfile, enabled ssl in it to get an https connection, and the wasi-browser now renders correctly in my local browser!
